<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Radio_Button_Female</name>
   <tag></tag>
   <elementGuidId>66b31d2a-484d-4849-a26c-ccb8f5303e22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-radio-1-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mat-radio-1-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ffed01c7-5c5e-400d-a53d-f50095496ad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>1ddb47b0-bc6c-424b-a06e-5a702d5005c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdc-radio__native-control</value>
      <webElementGuid>f7d62456-3bff-4611-9eea-b69cc65ae4e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-radio-1-input</value>
      <webElementGuid>cbd90bdd-974e-4594-bd32-e6ccd576a4b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mat-radio-group-0</value>
      <webElementGuid>08ce2ebf-1748-43e6-b472-2316a8436c14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Female</value>
      <webElementGuid>a7db2f98-18da-4489-bbe6-ca89fe86de0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>93a1de78-1499-4d52-9bbc-7c0b7281eff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-radio-1-input&quot;)</value>
      <webElementGuid>846f95bb-ab8b-422e-b15b-66111c3467a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mat-radio-1-input']</value>
      <webElementGuid>7ae320c5-1b2f-4434-89da-a3bacb469c7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-radio-button[@id='mat-radio-1']/div/div/input</value>
      <webElementGuid>2cdbd886-a067-4203-a94d-f6148c63c071</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-radio-button[2]/div/div/input</value>
      <webElementGuid>0910be24-7149-432e-9b2c-965fb95da703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'mat-radio-1-input' and @name = 'mat-radio-group-0']</value>
      <webElementGuid>10eee0f0-7193-4691-b72a-219c8503566c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
