<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Price Filter Slider</name>
   <tag></tag>
   <elementGuidId>38fe678a-0b12-4f8a-aec7-ed10ca928741</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.mdc-slider__input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='range']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cd3431bd-539b-4e9f-96c9-084691810456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>range</value>
      <webElementGuid>4ddce173-7f6e-4327-b1e9-1961b7be5099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdc-slider__input</value>
      <webElementGuid>f48bc3f4-c9a3-441e-85ee-a0defa757e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuetext</name>
      <type>Main</type>
      <value>8k</value>
      <webElementGuid>f5938987-bbdd-402d-86b2-dd50e65c9ea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>3494ea75-4f34-4255-b31c-b98211541732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>111</value>
      <webElementGuid>49499766-d252-47eb-b291-6b54eb514d0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>8264</value>
      <webElementGuid>d00ed1ba-ab57-4fe0-817f-df3efd7bf0fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/div[@class=&quot;container&quot;]/app-home[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row no-gutters pt-3 ng-star-inserted&quot;]/div[@class=&quot;col-md-3 col-sm-12&quot;]/div[@class=&quot;filter-container&quot;]/app-price-filter[1]/mat-card[@class=&quot;mat-mdc-card mdc-card my-4 ng-star-inserted&quot;]/mat-card-content[@class=&quot;mat-mdc-card-content&quot;]/mat-slider[@class=&quot;mat-mdc-slider mdc-slider m-0 mat-primary mdc-slider--discrete&quot;]/input[@class=&quot;mdc-slider__input&quot;]</value>
      <webElementGuid>ea5f13f9-173e-47a4-afa7-5f350a848fbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='range']</value>
      <webElementGuid>c330271a-4325-4f10-8b22-e7b30f4541f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-slider/input</value>
      <webElementGuid>604f4ec1-6c4d-4b29-a8f4-b565f1608b2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'range']</value>
      <webElementGuid>8102cdc9-f4e6-43c2-969a-c895510f5f8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
